2025-05-14 05:18:57,878 Not Found: / django.request WARNING
2025-05-14 05:18:57,914 Not Found: /favicon.ico django.request WARNING
2025-05-14 05:19:08,464 Not Found: /static/rest_framework/css/bootstrap.min.css django.request WARNING
2025-05-14 05:19:08,469 Not Found: /static/rest_framework/css/prettify.css django.request WARNING
2025-05-14 05:19:08,469 Not Found: /static/rest_framework/css/default.css django.request WARNING
2025-05-14 05:19:08,471 Not Found: /static/rest_framework/css/bootstrap-tweaks.css django.request WARNING
2025-05-14 05:19:08,473 Not Found: /static/rest_framework/js/jquery-3.7.1.min.js django.request WARNING
2025-05-14 05:19:08,473 Not Found: /static/rest_framework/js/bootstrap.min.js django.request WARNING
2025-05-14 05:19:08,477 Not Found: /static/rest_framework/js/ajax-form.js django.request WARNING
2025-05-14 05:19:08,477 Not Found: /static/rest_framework/js/prettify-min.js django.request WARNING
2025-05-14 05:19:08,477 Not Found: /static/rest_framework/js/default.js django.request WARNING
2025-05-14 05:19:08,478 Not Found: /static/rest_framework/js/load-ajax-form.js django.request WARNING
2025-05-14 05:19:08,479 Not Found: /static/rest_framework/js/csrf.js django.request WARNING
2025-05-14 05:20:30,436 Not Found: /static/rest_framework/css/bootstrap.min.css django.request WARNING
2025-05-14 05:20:30,437 Not Found: /static/rest_framework/css/bootstrap-tweaks.css django.request WARNING
2025-05-14 05:20:30,438 Not Found: /static/rest_framework/css/prettify.css django.request WARNING
2025-05-14 05:20:30,438 Not Found: /static/rest_framework/css/default.css django.request WARNING
2025-05-14 05:20:30,452 Not Found: /.well-known/appspecific/com.chrome.devtools.json django.request WARNING
2025-05-14 05:20:58,201 Internal Server Error: /api/tasks/ django.request ERROR
Traceback (most recent call last):
  File "C:\Python312\Lib\zoneinfo\_common.py", line 12, in load_tzdata
    return resources.files(package_name).joinpath(resource_name).open("rb")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\resources\_common.py", line 46, in wrapper
    return func(anchor)
           ^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\resources\_common.py", line 56, in files
    return from_package(resolve(anchor))
                        ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\resources\_common.py", line 82, in _
    return importlib.import_module(cand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\mixins.py", line 20, in create
    headers = self.get_success_headers(serializer.data)
                                       ^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\serializers.py", line 538, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\fields.py", line 1207, in to_representation
    value = self.enforce_timezone(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\fields.py", line 1150, in enforce_timezone
    field_timezone = self.timezone if hasattr(self, 'timezone') else self.default_timezone()
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\rest_framework\fields.py", line 1174, in default_timezone
    return timezone.get_current_timezone() if settings.USE_TZ else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\django\utils\timezone.py", line 66, in get_current_timezone
    return getattr(_active, "value", get_default_timezone())
                                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rmars\OneDrive\Desktop\projects\secure_tasker\venv\Lib\site-packages\django\utils\timezone.py", line 52, in get_default_timezone
    return zoneinfo.ZoneInfo(settings.TIME_ZONE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\zoneinfo\_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'
2025-05-14 05:20:58,279 Not Found: /.well-known/appspecific/com.chrome.devtools.json django.request WARNING
2025-05-14 05:28:04,918 Not Found: / django.request WARNING
2025-05-15 04:12:40,416 Not Found: / django.request WARNING
2025-05-15 04:18:48,373 Not Found: / django.request WARNING
2025-05-15 19:27:51,696 Unauthorized: /api/tasks/ django.request WARNING
2025-05-15 19:27:51,711 Unauthorized: /api/tasks/ django.request WARNING
